import de from 'trans/de';
import { PreloadableComponent } from 'utils/lazyWithPreload';

export { default as HomeScreen } from './home/HomeScreen';
export { default as SplashScreen } from './splash/SplashScreen';
export { default as LoginScreen } from './auth/LoginScreen';
export { default as MainTabScreen } from './main/MainTabScreen';
export { default as SettingsScreen } from './setting/SettingsScreen';
export { default as OnboardingScreen } from './onboarding/OnboardingScreen';
export { default as LanguageScreen } from './language/LanguageScreen';
export { default as PasswordScreen } from './auth/PasswordScreen';
export { default as VerifyOtpScreen } from './auth/VerifyOtpScreen';
export { default as CompleteProfileScreen } from './auth/CompleteProfileScreen';
export { default as CreatePasswordScreen } from './auth/CreatePasswordScreen';
export { default as CompletePictureProfileScreen } from './auth/CompletePictureProfileScreen';
export { default as WelcomScreen } from './auth/WelcomScreen';
export { default as SurveyStep1Screen } from './survey/SurveyStep1Screen';
export { default as SurveyStep2Screen } from './survey/SurveyStep2Screen';
export { default as SurveyStep3Screen } from './survey/SurveyStep3Screen';
export { default as MatchingScreen } from './matching/MatchingScreen';
export { default as ToolScreen } from './tool/ToolScreen';
export { default as ChatScreen } from './chat/ChatScreen';
export { default as NearbyScreen } from './nearby/NearbyScreen';
export { default as ProfileScreen } from './profile/ProfileScreen';
export { default as EditProfileScreen } from './profile/EditProfileScreen';
export { default as ListFriendScreen } from './profile/ListFriendScreen';
export { default as ProfilePartnerScreen } from './profilepartner/ProfilePartnerScreen';

export type RootStackParamList = {
  ToolsScreen: undefined;
  HomeScreen: undefined;
  SplashScreen: undefined;
  LoginScreen: { disableBack?: boolean };
  MainTabScreen: { trackingLogin?: boolean; isFirstOpen?: boolean };
  SettingsScreen: undefined;
  FriendRequestScreen: undefined;
  OnboardingScreen: undefined;
  LanguageScreen: undefined;
  PasswordScreen: undefined;
  VerifyOtpScreen: { phone: string };
  CompleteProfileScreen: undefined;
  CreatePasswordScreen: undefined;
  CompletePictureProfileScreen: undefined;
  WelcomScreen: undefined;
  SurveyStep1Screen: undefined;
  SurveyStep2Screen: undefined;
  SurveyStep3Screen: undefined;
  MatchingScreen: undefined;
  ToolScreen: undefined;
  ChatScreen: undefined;
  NearbyScreen: undefined;
  ProfileScreen: undefined;
  EditProfileScreen: undefined;
  ListFriendScreen: {
    activeTabIndex?: number;
  };
  ProfilePartnerScreen: {
    partner?: any;
  };
};
